version: '2'

services:

  mongo:
    image: mongo
    container_name: eb_mongo
    ports:
      - "27017:27017"

  mongo_admin:
    image: mongo-express
    container_name: eb_mongo_admin
    links:
      - mongo
    ports:
      - "8081:8081"

  redis:
    image: redis
    container_name: eb_redis
    ports:
      - "6379:6379"
