version: '2'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    depends_on:
      - logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-facility: "daemon"
        tag: "mongo"

  # auth:
  #   image: beevelop/nginx-basic-auth
  #   ports:
  #     - "8080:80"
  #   links:
  #     - mongo_admin:web
  #   environment:
  #     FORWARD_PORT: 8081
  #     # HTPASSWD: 'foo:$apr1$odHl5EJN$KbxMfo86Qdve2FH4owePn.' # TODO - password here isn't working (only foo:bar default is active)

  mongo_admin:
    image: mongo-express
    links:
      - mongo
    ports:
      - "8081:8081"
    depends_on:
      - logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-facility: "daemon"
        tag: "mongo-admin"

  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-facility: "daemon"
        tag: "redis"

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - logstash
  #   logging:
  #     driver: "syslog"
  #     options:
  #       syslog-address: "tcp://localhost:5000"
  #       syslog-facility: "daemon"
  #       tag: "nginx"

  # cerebro:
  #   image: yannart/cerebro
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch # NOTE - to use point Cerebro to http://elasticsearch:9200
  #     - logstash
  #   logging:
  #     driver: "syslog"
  #     options:
  #       syslog-address: "tcp://localhost:5000"
  #       syslog-facility: "daemon"
  #       tag: "cerebro"

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-facility: "daemon"
        tag: "kibana"

networks:
  elk:
