version: '2'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    depends_on:
      - logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-facility: "daemon"

  mongo_admin:
    image: mongo-express
    links:
      - mongo
    ports:
      - "8081:8081"
    depends_on:
      - logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-facility: "daemon"

  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-facility: "daemon"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-facility: "daemon"

  cerebro:
    image: yannart/cerebro
    ports:
      - "9000:9000"
    networks:
      - elk
    depends_on:
      - elasticsearch # NOTE - to use point Cerebro to http://elasticsearch:9200
      - logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-facility: "daemon"

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - eb_elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
